### ISSUE TITLE
Missing installation steps in Readme

### ISSUE THREAD

**Issue by dcoille** [Bonitasoft-Community/widget_autocompletekey#4]
Could you please make it clearer how to install the widget? A community user had the concern and I think it deserves a bit more of explanation.
Thx

**Comment by pierre-yves-monnet** [comment]
Hello,
This is an excellent point. You have to use the standard way to do that. I checked the Documentation on Bonita, to find where the "import a widget" is detailed
https://documentation.bonitasoft.com/bonita/7.11/_using-the-ui-designer
But I didn't find anything. You should open a ticket at the documentation github.

Saying that, here the way to import a widget (whatever the widget, its origin), is
1/ open the UI Designer,
2/ Click on "Import"
3/ give the ZIP that you downloaded
That's it, the widget should be visible on the Widget panel.

I don't want to do in double in the READ ME the Bonitasoft documentation, but, because the procedure is simple, I can copy that part in the README.
